config/routes.rb
Rails.application.routes.draw do
  resources :tasks_labels
  resources :labels
  root 'sessions#new'

  root 'usr#index'
  root to: "usr#index"
  resources :sessions
  resources :usrs
  resources :tasks
  # root 'tasks#index'

  # root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :usrs
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :usr
  validates :name, presence: true
  validates :content, presence: true
  validates :content, length: {minimum: 2, maximum: 20}
  validates_presence_of :usr_id
  # validate :start_datetime_cannot_be_later_than_end_datetime
  enum priority: [:low, :medium, :hight]
  has_many :tasks_labels
has_many :labels, :through => :tasks_labels
accepts_nested_attributes_for :tasks_labels, :reject_if => proc { |a|
   a['label_id'].blank? }
accepts_nested_attributes_for :labels
  # private
  # def start_datetime_cannot_be_later_than_end_datetime
  #   if start_date > end_date
  #     errors.add(:start_datetime, "Can not be set after the end date and time")
  #   end
 
  # end
  paginates_per 3

  def self.search(terms)
    if terms
      where('name LIKE ?, "#%{terms}"')
    else
      order('id desc')
  end
  end 
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_action :authenticate_usr!
  # before_action :logged_in
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  def index
    @tasks = if  params[:sort_expired]
      Task.order('end_date DESC').page(params[:page])
    elsif params[:sort_priority] 
      Task.order('priority DESC').page(params[:page])
    elsif params[:terms]
     Task.where('content like ? or status like ?', "%#{params[:terms]}%", "%#{params[:terms]}%").order('id ASC').page(params[:page])
    elsif  params[:key]
      Task.joins(:labels)
      .where("labels.name LIKE ?", "%#{params[:key]}%").page(params[:page])
  
    else
      Task.order('created_at DESC').page(params[:page])
    end
  end

  def search
    @task=task.search([:search])
  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = Task.create(task_params)

    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :content, :status, :priority, :usr_id, :terms, :start_date, :end_date, :key, label_ids:[])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="form22">
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_field :content, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :stutus %>
    <%= form.text_field :status, class:"form-control" %>
  </div>

  <div class="form-group">
  <%= form.label :priority %>
    <%= form.radio_button :priority, 'low' %> low  <%= form.radio_button :priority, 'medium' %> medium <%= form.radio_button :priority, 'hight' %> high
  </div>

  <div class="form-group">
   
    <%= form.hidden_field :usr_id %>
  </div>

  <div class="form-group">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="form-group">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>
    <div class="field">

    <%= form.hidden_field :usr_id, value: current_usr.id %>
  </div>
  <div class = "tables">
<% Label.all.each do |label| %>
  <% if label.usr.id == current_usr.id %>
  <%= form.label:name, label.name %>
<%= form.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
<% end %>
<% end %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="container">
<div class="menu">
<ul class="list">
<li><%= link_to 'New Task', new_task_path %></li>
<li><%= link_to 'sort expiration', tasks_path(sort_expired: 'true') %></li>
<li><%= link_to 'sort by priority', tasks_path(sort_priority: 'true') %></li>
<li><%= link_to 'New Label', new_label_path %></li>
</div>
<div class="show">
<%= form_tag(tasks_path, method: :get) do  %>
             <div class="form-inline my-2 my-lg-0">
               <%= text_field_tag :terms, params[:terms], placeholder: "search by content" %>
               <%= submit_tag 'Searche', name:nil %>
        
             </div>
           <% end %><br>
               <%= form_tag(tasks_path, method: :get) do %>
                  <%= text_field_tag :key, params[:key], placeholder: "search by label" %>
                  <%= submit_tag 'Search' %>
                <% end %>
<p id="notice"><%= notice %></p>
<h1><%= t('view.ALL TASKS')%></h1>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Status</th>
      <th>Priority</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3">Buttons</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <% if current_usr.id == task.usr_id %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.content %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= task.start_date %></td>
        <td><%= task.end_date %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= paginate @tasks %>
</div>
</div>

<br>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @task.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @task.end_date %>
</p>
<p> <h2> Labels attached to this task</h2>
<% @task.labels.each do |label| %>
<ul>
<li class = "user-tasks">
Title:<%= label.name + '       ' %> <br/>Content:<%= label.content %>
</li>
</ul>
<% end %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>